export const pagesRoutes = [
  ["v-f0388862","/links/",{"title":"Links"},["/links/index.html","/links/README.md"]],
  ["v-3044e74c","/posts/2021-12-24-hello-word.html",{"title":"Hello Word 1","subtitle":"A Test Post without the Header Image","date":"2021-12-24T00:00:00.000Z","tags":["test","tag with space"],"headerImage":"/img/in-post/2021-12-24/header.jpg","excerpt":"<p>Welcome to VuePress theme Gungnir.</p>\n"},["/posts/2021-12-24-hello-word","/posts/2021-12-24-hello-word.md"]],
  ["v-ea2bc074","/posts/2021-12-25-hello-word-with-header-image.html",{"title":"Hello Word 2","subtitle":"A Test Post with a Header Image","date":"2021-12-25T00:00:00.000Z","tags":["test","中文标签"],"headerImage":"/img/in-post/2021-12-25/header.jpg","excerpt":"<p>Welcome to VuePress theme Gungnir.</p>\n"},["/posts/2021-12-25-hello-word-with-header-image","/posts/2021-12-25-hello-word-with-header-image.md"]],
  ["v-610489c0","/posts/2022-05-23-hello-word-with-header-image-with-long-title.html",{"title":"Hello Word with a long title, it should require two lines to display","subtitle":"A Test Post with Comment Disabled","date":"2022-05-23T00:00:00.000Z","tags":["test"],"headerImage":"/img/in-post/2021-12-24/header.jpg","excerpt":"<p>Welcome to VuePress theme Gungnir.</p>\n"},["/posts/2022-05-23-hello-word-with-header-image-with-long-title","/posts/2022-05-23-hello-word-with-header-image-with-long-title.md"]],
  ["v-ba860320","/posts/2022-05-24-hello-word-4.html",{"title":"Hello World 4","subtitle":"A Test Post with Catalog Disabled","date":"2022-05-24T00:00:00.000Z","tags":["test"],"headerImage":"/img/in-post/2021-12-25/header.jpg","excerpt":"<p>Welcome to VuePress theme Gungnir.</p>\n"},["/posts/2022-05-24-hello-word-4","/posts/2022-05-24-hello-word-4.md"]],
  ["v-0badca45","/docs/advanced/analytics.html",{"title":"Analytics"},["/docs/advanced/analytics","/docs/advanced/analytics.md"]],
  ["v-31f7fb8c","/docs/advanced/comment.html",{"title":"Comment"},["/docs/advanced/comment","/docs/advanced/comment.md"]],
  ["v-611ed3a8","/docs/advanced/hitokoto.html",{"title":"Hitokoto"},["/docs/advanced/hitokoto","/docs/advanced/hitokoto.md"]],
  ["v-408a1831","/docs/advanced/icons.html",{"title":"Icons"},["/docs/advanced/icons","/docs/advanced/icons.md"]],
  ["v-1c54d1b9","/docs/advanced/reading-time.html",{"title":"Reading Time"},["/docs/advanced/reading-time","/docs/advanced/reading-time.md"]],
  ["v-e2314f0e","/docs/advanced/rss.html",{"title":"RSS"},["/docs/advanced/rss","/docs/advanced/rss.md"]],
  ["v-159e4297","/docs/md-enhance/chart.html",{"title":"Chart.js"},["/docs/md-enhance/chart","/docs/md-enhance/chart.md"]],
  ["v-2f957475","/docs/md-enhance/math.html",{"title":"Math Rendering"},["/docs/md-enhance/math","/docs/md-enhance/math.md"]],
  ["v-798e17cc","/docs/md-enhance/mermaid.html",{"title":"Mermaid"},["/docs/md-enhance/mermaid","/docs/md-enhance/mermaid.md"]],
  ["v-4702800c","/docs/md-enhance/others.html",{"title":"Others"},["/docs/md-enhance/others","/docs/md-enhance/others.md"]],
  ["v-3ab001db","/docs/basic/config.html",{"title":"Configuration"},["/docs/basic/config","/docs/basic/config.md"]],
  ["v-7e11c57c","/docs/basic/content.html",{"title":"Content"},["/docs/basic/content","/docs/basic/content.md"]],
  ["v-e5de223a","/docs/basic/installation.html",{"title":"Installation"},["/docs/basic/installation","/docs/basic/installation.md"]],
  ["v-105d0269","/docs/basic/intro.html",{"title":"Introduction"},["/docs/basic/intro","/docs/basic/intro.md"]],
  ["v-1980af35","/docs/basic/search.html",{"title":"Search"},["/docs/basic/search","/docs/basic/search.md"]],
  ["v-433a2c0a","/docs/plugins/baidu-tongji.html",{"title":"plugin-baidu-tongji"},["/docs/plugins/baidu-tongji","/docs/plugins/baidu-tongji.md"]],
  ["v-74489276","/docs/plugins/chart.html",{"title":"plugin-chart"},["/docs/plugins/chart","/docs/plugins/chart.md"]],
  ["v-3b837c3f","/docs/plugins/giscus.html",{"title":"plugin-giscus"},["/docs/plugins/giscus","/docs/plugins/giscus.md"]],
  ["v-b345de12","/docs/plugins/intro.html",{"title":"Plugins"},["/docs/plugins/intro","/docs/plugins/intro.md"]],
  ["v-6720eb72","/docs/plugins/katex.html",{"title":"plugin-katex"},["/docs/plugins/katex","/docs/plugins/katex.md"]],
  ["v-6b6cbb53","/docs/plugins/md-plus.html",{"title":"plugin-md-plus"},["/docs/plugins/md-plus","/docs/plugins/md-plus.md"]],
  ["v-103f387a","/docs/plugins/mermaid.html",{"title":"plugin-mermaid"},["/docs/plugins/mermaid","/docs/plugins/mermaid.md"]],
  ["v-21eae5e1","/docs/plugins/reading-time.html",{"title":"plugin-reading-time"},["/docs/plugins/reading-time","/docs/plugins/reading-time.md"]],
  ["v-75ea7751","/docs/plugins/rss.html",{"title":"plugin-rss"},["/docs/plugins/rss","/docs/plugins/rss.md"]],
  ["v-55b586ca","/zh/docs/basic/config.html",{"title":"基本配置"},["/zh/docs/basic/config","/zh/docs/basic/config.md"]],
  ["v-78864326","/zh/docs/basic/content.html",{"title":"内容"},["/zh/docs/basic/content","/zh/docs/basic/content.md"]],
  ["v-ac5676dc","/zh/docs/basic/installation.html",{"title":"安装"},["/zh/docs/basic/installation","/zh/docs/basic/installation.md"]],
  ["v-61a8b8cc","/zh/docs/basic/intro.html",{"title":"介绍"},["/zh/docs/basic/intro","/zh/docs/basic/intro.md"]],
  ["v-34863424","/zh/docs/basic/search.html",{"title":"搜索"},["/zh/docs/basic/search","/zh/docs/basic/search.md"]],
  ["v-28719ff4","/zh/docs/advanced/analytics.html",{"title":"站点统计"},["/zh/docs/advanced/analytics","/zh/docs/advanced/analytics.md"]],
  ["v-d8791e0a","/zh/docs/advanced/comment.html",{"title":"评论"},["/zh/docs/advanced/comment","/zh/docs/advanced/comment.md"]],
  ["v-b1d862c6","/zh/docs/advanced/hitokoto.html",{"title":"一言"},["/zh/docs/advanced/hitokoto","/zh/docs/advanced/hitokoto.md"]],
  ["v-9f7bc540","/zh/docs/advanced/icons.html",{"title":"图标支持"},["/zh/docs/advanced/icons","/zh/docs/advanced/icons.md"]],
  ["v-f4572cac","/zh/docs/advanced/reading-time.html",{"title":"阅读时长"},["/zh/docs/advanced/reading-time","/zh/docs/advanced/reading-time.md"]],
  ["v-ac264530","/zh/docs/advanced/rss.html",{"title":"RSS"},["/zh/docs/advanced/rss","/zh/docs/advanced/rss.md"]],
  ["v-763fc4d6","/zh/docs/extension/deploy.html",{"title":"部署"},["/zh/docs/extension/deploy","/zh/docs/extension/deploy.md"]],
  ["v-1938410f","/zh/docs/extension/resource.html",{"title":"资源"},["/zh/docs/extension/resource","/zh/docs/extension/resource.md"]],
  ["v-7769b806","/zh/docs/md-enhance/chart.html",{"title":"Chart.js"},["/zh/docs/md-enhance/chart","/zh/docs/md-enhance/chart.md"]],
  ["v-9243d5b4","/zh/docs/md-enhance/math.html",{"title":"数学公式渲染"},["/zh/docs/md-enhance/math","/zh/docs/md-enhance/math.md"]],
  ["v-d35c250a","/zh/docs/md-enhance/mermaid.html",{"title":"Mermaid"},["/zh/docs/md-enhance/mermaid","/zh/docs/md-enhance/mermaid.md"]],
  ["v-97bc0f2a","/zh/docs/md-enhance/others.html",{"title":"其他"},["/zh/docs/md-enhance/others","/zh/docs/md-enhance/others.md"]],
  ["v-3e5f51f9","/zh/docs/plugins/baidu-tongji.html",{"title":"plugin-baidu-tongji"},["/zh/docs/plugins/baidu-tongji","/zh/docs/plugins/baidu-tongji.md"]],
  ["v-0b86cfb6","/zh/docs/plugins/chart.html",{"title":"plugin-chart"},["/zh/docs/plugins/chart","/zh/docs/plugins/chart.md"]],
  ["v-a988fd24","/zh/docs/plugins/giscus.html",{"title":"plugin-giscus"},["/zh/docs/plugins/giscus","/zh/docs/plugins/giscus.md"]],
  ["v-27efac30","/zh/docs/plugins/intro.html",{"title":"插件"},["/zh/docs/plugins/intro","/zh/docs/plugins/intro.md"]],
  ["v-a667f73a","/zh/docs/plugins/katex.html",{"title":"plugin-katex"},["/zh/docs/plugins/katex","/zh/docs/plugins/katex.md"]],
  ["v-1a9547f8","/zh/docs/plugins/md-plus.html",{"title":"plugin-md-plus"},["/zh/docs/plugins/md-plus","/zh/docs/plugins/md-plus.md"]],
  ["v-d0f04daa","/zh/docs/plugins/mermaid.html",{"title":"plugin-mermaid"},["/zh/docs/plugins/mermaid","/zh/docs/plugins/mermaid.md"]],
  ["v-1d100bd0","/zh/docs/plugins/reading-time.html",{"title":"plugin-reading-time"},["/zh/docs/plugins/reading-time","/zh/docs/plugins/reading-time.md"]],
  ["v-34b91882","/zh/docs/plugins/rss.html",{"title":"plugin-rss"},["/zh/docs/plugins/rss","/zh/docs/plugins/rss.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-15534fdd","/tags/",{"title":"Tags"},["/tags/index.html"]],
  ["v-8daa1a0e","/",{"title":"Home"},["/index.html"]],
  ["v-d5d13fc0","/tags/test/",{"title":"test | Tags"},["/tags/test/index.html"]],
  ["v-2d0ad528","/zh/",{"title":"Home"},["/zh/index.html"]],
  ["v-781133a0","/tags/tag-with-space/",{"title":"tag with space | Tags"},["/tags/tag-with-space/index.html"]],
  ["v-6bc6ea4a","/tags/%E4%B8%AD%E6%96%87%E6%A0%87%E7%AD%BE/",{"title":"中文标签 | Tags"},["/tags/中文标签/","/tags/%E4%B8%AD%E6%96%87%E6%A0%87%E7%AD%BE/index.html"]],
  ["v-2c44730e","/zh/tags/",{"title":"标签"},["/zh/tags/index.html"]],
  ["v-3a1f8885","/page/1/",{"title":"Home"},["/page/1/index.html"]],
]
